tunnel: 2eb44747-8c77-4ea5-a0f8-f23885737818
credentials-file: /etc/cloudflared/2eb44747-8c77-4ea5-a0f8-f23885737818.json

ingress:
  - hostname: anytext.chaotic-aur.coarde.com
    service: http://10.7.0.4:80
  - service: http_status:404
