FROM alpine:latest
RUN wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64 -O /bin/cloudflared
RUN chmod +x /bin/cloudflared
COPY 2eb44747-8c77-4ea5-a0f8-f23885737818.json /root/.cloudflared/
COPY config.yml /root/.cloudflared/
ENTRYPOINT cloudflared --no-autoupdate tunnel run
